# RocketMQ Broker 配置（开发环境）
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

# 自动创建 Topic（开发环境方便）
autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true
